version: '3.8'
services:
  db:
    container_name: locateme
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locatemeDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3307:3306"
    volumes:
      - ~/docker/mysql:/db
volumes:
  locatemeSQL: ~