### POST login
POST http://localhost:7000/auth/login/
Content-Type: application/json

{
  "mail": "admin",
  "password": "admin"
}

### POST change password
POST http://localhost:7000/auth/change-password
Content-Type: application/json
auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2NjE1MTc0MTcsImV4cCI6MTY2MTUyMTAxN30.o6_TNlGCp1IQQdInvdLzeDvdBm0B1YA1f5mFNcLoogo

{
  "oldPassword": "admin2",
  "newPassword" : "admin"
}