### GET request all users
GET http://localhost:7000/users/
Accept: application/json

### GET request 1 user
GET http://localhost:7000/users/1/
Accept: application/json

### Send POST request with json body
POST http://localhost:7000/create
Content-Type: application/json

{
  "mail": "test2@test.com",
  "password": "motdepasse2"
}

### Send PUT request with json body
PUT http://localhost:7000/update/2
Accept: application/json
Content-Type: application/json

{
  "mail": "updatedEmail@test.com",
  "password": "motdepasseUpdated"
}

### Send DELETE request
DELETE http://localhost:7000/delete/2